# Server Port
server.port=8080

# JWT Configuration
app.jwt.secret=mysecretkey
app.jwt.expiration=86400000  # 1 day in milliseconds

# Spring Data JPA (H2 Database)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Actuator Endpoints
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
